#!/usr/bin/env bash
set -euo pipefail
shopt -s inherit_errexit 2> /dev/null || true

installer_script_dir() {
  cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd
}

INSTALLER_SCRIPT_DIR="$(installer_script_dir)"
readonly INSTALLER_SCRIPT_DIR
export DARKSIDEOS_INSTALLER_ROOT="${DARKSIDEOS_INSTALLER_ROOT:-${INSTALLER_SCRIPT_DIR}}"
export DARKSIDEOS_INSTALLER_SHARED="${DARKSIDEOS_INSTALLER_SHARED:-${DARKSIDEOS_INSTALLER_ROOT}/shared}"
export DARKSIDEOS_INSTALLER_DOMAIN="${DARKSIDEOS_INSTALLER_DOMAIN:-${DARKSIDEOS_INSTALLER_ROOT}/domain}"
export DARKSIDEOS_INSTALLER_PRESENTATION="${DARKSIDEOS_INSTALLER_PRESENTATION:-${DARKSIDEOS_INSTALLER_ROOT}/presentation}"
export DARKSIDEOS_INSTALLER_APPLICATION="${DARKSIDEOS_INSTALLER_APPLICATION:-${DARKSIDEOS_INSTALLER_ROOT}/application}"
export DARKSIDEOS_INSTALLER_DTOS="${DARKSIDEOS_INSTALLER_DTOS:-${DARKSIDEOS_INSTALLER_APPLICATION}/dtos}"
export DARKSIDEOS_INSTALLER_SERVICES="${DARKSIDEOS_INSTALLER_SERVICES:-${DARKSIDEOS_INSTALLER_APPLICATION}/services}"
export DARKSIDEOS_INSTALLER_USE_CASES="${DARKSIDEOS_INSTALLER_USE_CASES:-${DARKSIDEOS_INSTALLER_APPLICATION}/use-cases}"
export DARKSIDEOS_INSTALLER_INFRASTRUCTURE="${DARKSIDEOS_INSTALLER_INFRASTRUCTURE:-${DARKSIDEOS_INSTALLER_ROOT}/infrastructure}"
export DARKSIDEOS_INSTALLER_REPOSITORIES="${DARKSIDEOS_INSTALLER_REPOSITORIES:-${DARKSIDEOS_INSTALLER_INFRASTRUCTURE}/repositories}"
export DARKSIDEOS_INSTALLER_SYSTEM="${DARKSIDEOS_INSTALLER_SYSTEM:-${DARKSIDEOS_INSTALLER_INFRASTRUCTURE}/system}"
export DARKSIDEOS_INSTALLER_GENERATORS="${DARKSIDEOS_INSTALLER_GENERATORS:-${DARKSIDEOS_INSTALLER_INFRASTRUCTURE}/generators}"

# This entrypoint wires one explicit use case. Domain, application,
# presentation, and infrastructure modules stay separated under iso/scripts.
# shellcheck source=/dev/null
source "${DARKSIDEOS_INSTALLER_USE_CASES}/create-new-host.sh"

run_create_new_host "$@"
