# shellcheck shell=bash
# Host scaffold generation after the final installation confirmation.

escape_nix_string() {
  local value="$1"

  value="${value//\\/\\\\}"
  value="${value//\"/\\\"}"
  value="${value//\$\{/\\\$\{}"

  printf '%s\n' "$value"
}

write_generated_file_idempotent() {
  local target_path="$1"
  local label="$2"
  shift 2

  local target_dir
  target_dir="$(dirname "$target_path")" || return

  local temp_path
  temp_path="$(mktemp -p "$target_dir" ".${target_path##*/}.XXXXXX")" || return

  if ! "$@" > "$temp_path"; then
    rm -f -- "$temp_path"
    return 1
  fi

  if [[ -e "$target_path" ]]; then
    if cmp -s "$temp_path" "$target_path"; then
      rm -f -- "$temp_path"
      log_info "Reusing existing ${label}: ${target_path}"
      return
    fi

    rm -f -- "$temp_path"
    die "Existing ${label} does not match the requested installation plan: ${target_path}"
  fi

  mv "$temp_path" "$target_path"
  log_info "Created ${label}: ${target_path}"
}

print_host_default_nix() {
  local host_name="$1"
  local state_version="$2"
  local shared_modules="$3"
  local hardware_modules="$4"
  local module_name

  printf '# Host configuration for %s.\n' "$host_name"
  printf '# Generated by darksideos-install.\n'
  printf '{...}: {\n'
  printf '  imports = [\n'
  printf '    # Disk layout\n'
  printf '    (import ./disk.nix {})\n'
  printf '\n'
  printf '    # Detected hardware\n'
  printf '    ./hardware-configuration.nix\n'

  if [[ -n "$shared_modules" ]]; then
    printf '\n'
    printf '    # Shared modules\n'
    while IFS= read -r module_name; do
      [[ -n "$module_name" ]] || continue
      printf '    ../../shared-modules/%s\n' "$module_name"
    done < <(lines_from_csv "$shared_modules")
  fi

  if [[ -n "$hardware_modules" ]]; then
    printf '\n'
    printf '    # Hardware modules\n'
    while IFS= read -r module_name; do
      [[ -n "$module_name" ]] || continue
      printf '    ../../shared-modules/hardware/%s\n' "$module_name"
    done < <(lines_from_csv "$hardware_modules")
  fi

  printf '  ];\n'
  printf '\n'
  printf '  sops = {\n'
  printf '    defaultSopsFile = ./secrets/%s.yaml;\n' "$host_name"
  printf '  };\n'
  printf '\n'
  printf '  # System state version. Do not change after install.\n'
  printf '  system.stateVersion = "%s";\n' "$state_version"
  printf '}\n'
}

print_host_disk_nix() {
  local host_name="$1"
  local partitioning_layout="$2"
  local partitioning_disk="$3"
  local escaped_partitioning_disk

  escaped_partitioning_disk="$(escape_nix_string "$partitioning_disk")" || return

  case "$partitioning_layout" in
    "$PARTITIONING_LAYOUT_ROOT_ON_RAM_SSD_ENCRYPT")
      printf '# Disk layout for %s.\n' "$host_name"
      printf '# Generated by darksideos-install.\n'
      printf '{\n'
      printf '  luksPasswordFile ? null,\n'
      printf '  ...\n'
      printf '}:\n'
      printf 'import ../../shared-lib/disko/root-on-ram-ssd-encrypt.nix {\n'
      printf '  diskDevice = "%s";\n' "$escaped_partitioning_disk"
      printf '  inherit luksPasswordFile;\n'
      printf '  swapSize = "32G";\n'
      printf '}\n'
      ;;
    *)
      die "Unsupported Disko layout for host scaffold: ${partitioning_layout}"
      ;;
  esac
}

create_host_scaffold() {
  local repo_root="$1"
  local host_name="$2"
  local state_version="$3"
  local partitioning_layout="$4"
  local partitioning_disk="$5"
  local shared_modules="$6"
  local hardware_modules="$7"

  local host_dir="${repo_root}/hosts/${host_name}"
  local secrets_dir="${host_dir}/secrets"

  [[ ! -e "$host_dir" || -d "$host_dir" ]] || die "Host path exists but is not a directory: hosts/${host_name}"

  install -d -m 0755 "$host_dir"
  install -d -m 0700 "$secrets_dir"

  write_generated_file_idempotent \
    "${host_dir}/default.nix" \
    "host entrypoint" \
    print_host_default_nix "$host_name" "$state_version" "$shared_modules" "$hardware_modules"

  write_generated_file_idempotent \
    "${host_dir}/disk.nix" \
    "Disko layout" \
    print_host_disk_nix "$host_name" "$partitioning_layout" "$partitioning_disk"

  log_info "Host scaffold ready: hosts/${host_name}"
}
